version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-query-devtools
    versions:
    - "> 2.4.7"
  - dependency-name: uuid
    versions:
    - "> 3.4.0"
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.4
  - dependency-name: electron
    versions:
    - 11.2.2
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: electron-log
    versions:
    - 4.3.2
    - 4.3.3
  - dependency-name: "@bugsnag/js"
    versions:
    - 7.8.0
    - 7.9.0
  - dependency-name: dotenv-webpack
    versions:
    - 6.0.2
    - 6.0.4
    - 7.0.1
  - dependency-name: "@types/wavesurfer.js"
    versions:
    - 3.3.2
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: electron-dl
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: "@bugsnag/plugin-react"
    versions:
    - 7.7.0
  - dependency-name: wavesurfer.js
    versions:
    - 4.5.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: react-use
    versions:
    - 17.0.2
    - 17.1.0
    - 17.1.1
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.16
    - 8.0.17
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: nucleus-nodejs
    versions:
    - 3.0.8
